In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
df

In [ ]:
!python /content/sample_data/code/Main.py

Read Raw Data File:
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
Customer ID     object
Country         object
dtype: object
(1348144, 8)


Preprocessed Raw Data File:
Customer ID            object
InvoiceDate    datetime64[ns]
StockCode              object
Quantity                int64
dtype: object
(957968, 4)


Purchase Sequence:
Transaction_Rank
Customer ID            object
InvoiceDate    datetime64[ns]
StockCode              object
0                     float64
1                     float64
                    ...
98                    float64
99                    float64
100                   float64
101                   float64
102                   float64
Length: 106, dtype: object
(85727, 106)


Total Splits: 366
Processing DF: 0
Processing DF: 1
Processing DF: 2
Processing DF: 3
Processing DF: 4
Processing DF: 5
Processing DF: 6
Processing DF: 7
Processing DF: 8
Processing DF: 9
Processing DF: 10
Processing DF: 11
Processing DF: 12
Processing DF: 13
Processing DF: 14
Processing DF: 15
Processing DF: 16
Processing DF: 17
Processing DF: 18
Processing DF: 19
Processing DF: 20
Processing DF: 21
Processing DF: 22
Processing DF: 23
Processing DF: 24
Processing DF: 25
Processing DF: 26
Processing DF: 27
Processing DF: 28
Processing DF: 29
Processing DF: 30
Processing DF: 31
Processing DF: 32
Processing DF: 33
Processing DF: 34
Processing DF: 35
Processing DF: 36
Processing DF: 37
Processing DF: 38
Processing DF: 39
Processing DF: 40
Processing DF: 41
Processing DF: 42
Processing DF: 43
Processing DF: 44
Processing DF: 45
Processing DF: 46
Processing DF: 47
Processing DF: 48
Processing DF: 49
Processing DF: 50
Processing DF: 51
Processing DF: 52
Processing DF: 53
Processing DF: 54
Processing DF: 55
Processing DF: 56
Processing DF: 57
Processing DF: 58
Processing DF: 59
Processing DF: 60
Processing DF: 61
Processing DF: 62
Processing DF: 63
Processing DF: 64
Processing DF: 65
Processing DF: 66
Processing DF: 67
Processing DF: 68
Processing DF: 69
Processing DF: 70
Processing DF: 71
Processing DF: 72
Processing DF: 73
Processing DF: 74
Processing DF: 75
Processing DF: 76
Processing DF: 77
Processing DF: 78
Processing DF: 79
Processing DF: 80
Processing DF: 81
Processing DF: 82
Processing DF: 83
Processing DF: 84
Processing DF: 85
Processing DF: 86
Processing DF: 87
Processing DF: 88
Processing DF: 89
Processing DF: 90
Processing DF: 91
Processing DF: 92
Processing DF: 93
Processing DF: 94
Processing DF: 95
Processing DF: 96
Processing DF: 97
Processing DF: 98
Processing DF: 99
Processing DF: 100
Processing DF: 101
Processing DF: 102
Processing DF: 103
Processing DF: 104
Processing DF: 105
Processing DF: 106
Processing DF: 107
Processing DF: 108
Processing DF: 109
Processing DF: 110
Processing DF: 111
Processing DF: 112
Processing DF: 113
Processing DF: 114
Processing DF: 115
Processing DF: 116
Processing DF: 117
Processing DF: 118
Processing DF: 119
Processing DF: 120
Processing DF: 121
Processing DF: 122
Processing DF: 123
Processing DF: 124
Processing DF: 125
Processing DF: 126
Processing DF: 127
Processing DF: 128
Processing DF: 129
Processing DF: 130
Processing DF: 131
Processing DF: 132
Processing DF: 133
Processing DF: 134
Processing DF: 135
Processing DF: 136
Processing DF: 137
Processing DF: 138
Processing DF: 139
Processing DF: 140
Processing DF: 141
Processing DF: 142
Processing DF: 143
Processing DF: 144

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_1 = pd.read_csv("/content/drive/My Drive/data_1.csv",sep =";", encoding = "cp1251", error_bad_lines=False)
df_2 = pd.read_csv("/content/drive/My Drive/data_2.csv",sep = ";", encoding = "cp1251", error_bad_lines=False)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
df_all = pd.concat([df_1, df_2])

In [ ]:
df = df_all
df.drop_duplicates()

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,3,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051334048,0,NaN
1,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,4,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051367351,0,NaN
2,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,7,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00007611755,0,NaN
3,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,1,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00014478250,0,NaN
4,01.07.2017 0:00,06.07.2017 0:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,9,1,30.06.2017 0:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00001209351,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876070,31.10.2017 23:59,02.11.2017 0:00,6005071_ES,К отгрузке,3 222,3 222,Курьерская,Наличная,Москва,КОСМЕТИКА/ГИГИЕНА,...,150,3,2,31.10.2017 0:00,55574953-52575355515475,109117_mu19@inbox.ru,Мария,IDL00039538654,0,NaN
876071,31.10.2017 23:59,02.11.2017 0:00,6005071_ES,К отгрузке,3 222,3 222,Курьерская,Наличная,Москва,КОСМЕТИКА/ГИГИЕНА,...,150,2,2,31.10.2017 0:00,55574953-52575355515475,109117_mu19@inbox.ru,Мария,IDL00039538755,0,NaN
876072,31.10.2017 23:59,03.11.2017 0:00,6005077_ES,Возврат из ПВЗ,2 564,2 564,Магазины,Безналичная,Москва,ИГРУШКИ,...,0,1,0,31.10.2017 0:00,55574857-54545754565577,97117_au19@mail.ru,Дмитрий,IDL00043615553,0,NaN
876073,31.10.2017 23:59,03.11.2017 0:00,6005089_ES,Возврат из ПВЗ,2 564,2 564,Магазины,Безналичная,Москва,ИГРУШКИ,...,0,1,0,31.10.2017 0:00,55574857-54545754565577,97117_au19@mail.ru,Дмитрий,IDL00043615553,0,NaN
876074,31.10.2017 23:59,03.11.2017 0:00,6005101_ES,Доставлен,848,848,Магазины,Безналичная,Москва,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,...,0,1,2,31.10.2017 0:00,55575054-56564948515679,112109_pm21@gmail.com,Иванов,IDL00032748755,0,NaN

In [ ]:
df['Группа4']

0                          носки
1                          носки
2                          носки
3                          носки
4                       колготки
                   ...
876070    кондиционеры для белья
876071    кондиционеры для белья
876072           треки, парковки
876073           треки, парковки
876074           пеленки и лотки
Name: Группа4, Length: 1673267, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1348144 entries, 0 to 876074
Data columns (total 35 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   Дата                      1348144 non-null  object
 1   ДатаДоставки              1346919 non-null  object
 2   НомерЗаказаНаСайте        1348144 non-null  object
 3   НовыйСтатус               1348144 non-null  object
 4   СуммаЗаказаНаСайте        1348144 non-null  float64
 5   СуммаДокумента            1348144 non-null  object
 6   МетодДоставки             1348030 non-null  object
 7   ФормаОплаты               1348028 non-null  object
 8   Регион                    1338330 non-null  object
 9   Группа2                   1348144 non-null  object
 10  Группа3                   1348144 non-null  object
 11  Группа4                   1291998 non-null  object
 12  Тип                       1348144 non-null  object
 13  Номенклатура              1348144 non-null  object
 14  ТипТовара                 1348144 non-null  object
 15  Отменено                  1348144 non-null  object
 16  Количество                1348144 non-null  int64
 17  Цена                      1348144 non-null  float64
 18  СуммаСтроки               1348144 non-null  float64
 19  ЦенаЗакупки               1343301 non-null  object
 20  МесяцДатыЗаказа           1348144 non-null  int64
 21  ГодДатыЗаказа             1348144 non-null  object
 22  Статус                    1348144 non-null  object
 23  Гео                       1348144 non-null  object
 24  Маржа                     1343301 non-null  float64
 25  СуммаУслуг                1348144 non-null  int64
 26  СуммаДоставки             1348144 non-null  object
 27  НомерСтроки               1348144 non-null  int64
 28  КоличествоПроданоКлиенту  1348144 non-null  int64
 29  ДатаЗаказаНаСайте         1348144 non-null  object
 30  Телефон_new               1348144 non-null  object
 31  ЭлектроннаяПочта_new      1327060 non-null  object
 32  Клиент                    1347793 non-null  object
 33  ID_SKU                    1348144 non-null  object
 34  ГородМагазина             1348144 non-null  object
dtypes: float64(4), int64(5), object(26)
memory usage: 370.3+ MB

In [ ]:
df.drop(['ПричинаОтмены', 'МагазинЗаказа', 'ПВЗ_код'], axis='columns', inplace=True)

In [ ]:
df = df.dropna(axis = 0, thresh = 30)

In [ ]:
numeric_columns = ['СуммаЗаказаНаСайте', 'Цена', 'Маржа', 'СуммаУслуг', 'СуммаСтроки']
for column in numeric_columns:
    df[column] = df[column].replace(r'\s+','',regex=True)
    df[column] = df[column].replace(',','.',regex=True)
    df[column] = df[column].apply(pd.to_numeric)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
df_for_nn = df[['НомерЗаказаНаСайте', 'ID_SKU', 'Группа4', 'Количество', 'ДатаДоставки', 'Цена', 'Телефон_new', 'ГородМагазина']]

In [ ]:
df_for_nn = df_for_nn.rename({'НомерЗаказаНаСайте': 'InvoiceNo', 'ID_SKU': 'StockCode', 'Группа4': 'Description', 'Количество': 'Quantity', 'ДатаДоставки': 'InvoiceDate', 'Цена': 'UnitPrice','Телефон_new':'Customer ID', 'ГородМагазина':'Country'}, axis = 1)

In [ ]:
df_for_nn.to_csv('data.csv')

In [ ]:
df_for_nn = df_for_nn.rename({'CustomerID':'Customer ID'}, axis = 1)

In [ ]:
df_for_nn.to_csv('data.csv', index = False)